[package]
name = "mine_nbt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.24"
byteorder = "1.4.3"
iter-read = "0.3.1"
paste = "1.0.3"
quote = "1.0.21"

[lib]
proc-macro = true